### ISSUE TITLE
Fall back  to ip geolocation

### ISSUE THREAD

**Issue by Haroenv** [derhuerst/location#1]
Although browsers support geolocation on every platform, there doesn't seem to be a all-compassing package yet. 

I'd suggest falling back to geolocation via ip (https://github.com/bluesmoon/node-geoip), or looking up the individual APIs (i.e. Windows has this: https://msdn.microsoft.com/en-us/library/gg589513(v=vs.85).aspx)

**Comment by derhuerst** [comment]
> Although browsers support geolocation on every platform, there doesn't seem to be a all-compassing package yet.

Seems like it. I tried to abuse [phantomjs](http://phantomjs.org/), but [geolocation seems to be disabled/unsupported](http://stackoverflow.com/questions/15894090/does-phantomjs-support-geolocations).

> I'd suggest falling back to geolocation via ip (https://github.com/bluesmoon/node-geoip), or looking up the individual APIs (i.e. Windows has this: https://msdn.microsoft.com/en-us/library/gg589513(v=vs.85).aspx)

I strongly disagree. Geolocation via (external) IP address can be extremely inaccurate, especially with

- the worldwide IPv4/NAT internet landscape,
- cellular networks,
- Proxies, VPNs.

I'd rather provide a decent way for applications to handle geolocation not being available than to (more or less) randomly guess. I'm just afraid people that people will, using this project, blindly rely on geolocation and therefore patronize users.

If you want, you can help implement a (real geolocation) Windows intregration into this module.
