### ISSUE TITLE
MacOS only?

### ISSUE THREAD

**Issue by zeke** [derhuerst/location#2]
It looks like this only works on MacOS. https://github.com/fulldecent/corelocationcli/

Is that correct? If so, it should probably be noted in the README.

**Comment by derhuerst** [comment]
I had added this locally but didn't push it:

```md
*Linux or Windows user?* Help me support them with this module!
```

**Comment by derhuerst** [comment]
I'm pretty sure it's possible to do it on Windows. Not sure about Linux, I just came across geoip services yet.

**Comment by derhuerst** [comment]
I'm working on integrating [`wifi-triangulate`](https://github.com/watson/wifi-triangulate) into this module right now.

**Comment by derhuerst** [comment]
Also working on an isomorphic version that uses the [geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation).

**Comment by zeke** [comment]
👍

**Comment by derhuerst** [comment]
See [`isomorphic-location`](https://github.com/derhuerst/isomorphic-location).

**Comment by derhuerst** [comment]
For Windows, a simplified version of [PowerLocate](https://github.com/0sm0s1z/PowerLocate) might be interesting.

**Comment by derhuerst** [comment]
Closing because of 30663a8e12d64352d67521a0b2c4696051d8c66c.
